"use client";

import React, { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";
import {
  BarChart3,
  PiggyBank,
  DollarSign,
  Coins,
  Cpu,
  RefreshCw,
  TrendingUp,
  Loader2,
} from "lucide-react";
import { api, UserStats } from "@/lib/api";

export default function DashboardPage() {
  const [stats, setStats] = useState<UserStats | null>(null);
  const [loading, setLoading] = useState(true);

  const loadStats = async () => {
    setLoading(true);
    try {
      const data = await api.getStats();
      setStats(data);
    } catch (err) {
      console.error("Error fetching dashboard stats:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadStats();
  }, []);

  // Helper for computing model name tags
  const formatModelName = (name: string) => {
    if (name.includes("flash")) return "Gemini 1.5 Flash";
    if (name.includes("pro")) return "Gemini 1.5 Pro";
    if (name.includes("groq") || name.includes("llama")) return "Groq Llama 3";
    if (name.includes("deepseek")) return "DeepSeek V3";
    return name;
  };

  // Helper for model badge colors based on exact user system
  const getBadgeColors = (name: string) => {
    const n = name.toLowerCase();
    if (n.includes("pro")) return { className: "border border-card-border border-l-2 border-l-indigo-500 bg-indigo-500/10 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 font-medium", color: "#6366f1" };
    if (n.includes("flash")) return { className: "border border-card-border border-l-2 border-l-violet-500 bg-violet-500/10 dark:bg-violet-500/15 text-violet-600 dark:text-violet-400 font-medium", color: "#7c3aed" };
    if (n.includes("groq") || n.includes("llama")) return { className: "border border-card-border border-l-2 border-l-emerald-500 bg-emerald-500/10 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 font-medium", color: "#10b981" };
    if (n.includes("deepseek")) return { className: "border border-card-border border-l-2 border-l-blue-500 bg-blue-500/10 dark:bg-blue-500/15 text-blue-600 dark:text-blue-400 font-medium", color: "#3b82f6" };
    return { className: "border border-card-border border-l-2 border-l-zinc-500 bg-zinc-500/10 dark:bg-zinc-500/15 text-zinc-600 dark:text-zinc-400 font-medium", color: "#71717a" };
  };

  // Calculate percentages for SVG donut chart
  const modelBreakdown = stats?.model_breakdown || [];
  const totalModelCalls = modelBreakdown.reduce((sum, item) => sum + item.count, 0) || 1;

  let accumulatedAngle = 0;
  const donutSegments = modelBreakdown.map((item) => {
    const percentage = item.count / totalModelCalls;
    const angle = percentage * 360;
    const startAngle = accumulatedAngle;
    accumulatedAngle += angle;

    // SVG arc calculations
    const x1 = 50 + 40 * Math.cos((startAngle - 90) * (Math.PI / 180));
    const y1 = 50 + 40 * Math.sin((startAngle - 90) * (Math.PI / 180));
    const x2 = 50 + 40 * Math.cos((startAngle + angle - 90) * (Math.PI / 180));
    const y2 = 50 + 40 * Math.sin((startAngle + angle - 90) * (Math.PI / 180));
    const largeArcFlag = angle > 180 ? 1 : 0;

    const pathData = `M 50 50 L ${x1} ${y1} A 40 40 0 ${largeArcFlag} 1 ${x2} ${y2} Z`;

    return {
      model: item.model,
      path: pathData,
      percentage,
      color: getBadgeColors(item.model).color,
    };
  });

  return (
    <div className="flex h-screen bg-background text-primary-text overflow-hidden font-sans">
      <Sidebar />

      {/* Main Stats Panel */}
      <div className="flex-1 overflow-y-auto p-8 max-w-5xl mx-auto space-y-8 relative">
        <div className="absolute top-[10%] left-[5%] w-96 h-96 rounded-full bg-accent-violet/5 blur-[120px] pointer-events-none animate-pulse-glow" />

        {/* Title Header */}
        <div className="border-b border-card-border pb-5 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-medium tracking-tight flex items-center gap-3">
              <BarChart3 className="text-accent-violet w-7 h-7" />
              Routing & Cost Analytics
            </h1>
            <p className="text-xs text-secondary-text">
              Monitor your cumulative API savings and routing metrics generated by OmniMind's cognitive brokers.
            </p>
          </div>
          <button
            type="button"
            onClick={loadStats}
            className="p-2.5 rounded-lg border border-card-border bg-card-bg hover:bg-muted-surface text-accent-violet hover:text-accent-violet-hover cursor-pointer shadow transition-colors duration-150"
            title="Refresh Metrics"
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
          </button>
        </div>

        {loading ? (
          <div className="h-96 flex flex-col items-center justify-center space-y-4">
            <Loader2 className="animate-spin text-accent-violet w-8 h-8" />
            <p className="text-xs text-muted-text italic">Compiling transaction records and log databases...</p>
          </div>
        ) : !stats || stats.total_messages === 0 ? (
          <div className="p-8 rounded-xl text-center space-y-3 max-w-md mx-auto mt-12 border border-card-border bg-card-bg">
            <TrendingUp size={32} className="text-muted-text/30 mx-auto animate-pulse" />
            <h3 className="text-xs font-medium text-primary-text">No Analytics Logged</h3>
            <p className="text-[11px] text-secondary-text leading-relaxed">
              Start chat conversations first. OmniMind will record model token footprints and log savings indices here.
            </p>
          </div>
        ) : (
          <div className="space-y-8">
            {/* Grid 1: Aggregate Cards */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-5">
              {/* Savings Card */}
              <div className="p-5 rounded-xl border border-success-val/20 bg-gradient-to-br from-success-val/5 to-success-val/10 relative overflow-hidden">
                <div className="absolute right-[-10px] bottom-[-10px] text-success-val/5 rotate-12">
                  <PiggyBank size={80} />
                </div>
                <p className="text-[11px] font-medium text-success-val uppercase tracking-widest">Total Savings</p>
                <p className="text-2xl font-medium text-success-val font-mono mt-2">
                  ${stats.total_savings.toFixed(4)}
                </p>
                <p className="text-[8px] text-muted-text mt-1">Footprint vs Premium Tiers</p>
              </div>

              {/* Cost Card */}
              <div className="p-5 rounded-xl border border-card-border bg-card-bg">
                <p className="text-[11px] font-medium text-accent-violet uppercase tracking-widest">Total Cost (USD)</p>
                <p className="text-2xl font-medium text-primary-text font-mono mt-2">
                  ${stats.total_cost.toFixed(4)}
                </p>
                <p className="text-[8px] text-muted-text mt-1">Real operational expenditure</p>
              </div>

              {/* Tokens Card */}
              <div className="p-5 rounded-xl border border-card-border bg-card-bg">
                <p className="text-[11px] font-medium text-secondary-text uppercase tracking-widest">Total Tokens</p>
                <p className="text-2xl font-medium text-primary-text font-mono mt-2">
                  {(stats.total_input_tokens + stats.total_output_tokens).toLocaleString()}
                </p>
                <p className="text-[8px] text-muted-text mt-1">
                  I: {stats.total_input_tokens.toLocaleString()} | O: {stats.total_output_tokens.toLocaleString()}
                </p>
              </div>

              {/* Messages Card */}
              <div className="p-5 rounded-xl border border-card-border bg-card-bg">
                <p className="text-[11px] font-medium text-secondary-text uppercase tracking-widest">Turn Invocations</p>
                <p className="text-2xl font-medium text-primary-text font-mono mt-2">
                  {stats.total_messages}
                </p>
                <p className="text-[8px] text-muted-text mt-1">Total model transactions</p>
              </div>
            </div>

            {/* Grid 2: Donut Chart & Model Invocations list */}
            <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
              {/* Circular distribution chart */}
              <div className="p-6 rounded-xl border border-card-border bg-card-bg md:col-span-5 flex flex-col items-center justify-center space-y-4">
                <h3 className="text-[11px] font-medium text-zinc-500 uppercase tracking-widest self-start">Model Distribution</h3>
                <div className="relative w-40 h-40">
                  <svg viewBox="0 0 100 100" className="w-full h-full rotate-[-90deg]">
                    {donutSegments.map((seg, i) => (
                      <path
                        key={i}
                        d={seg.path}
                        fill="none"
                        stroke={seg.color}
                        strokeWidth="12"
                        strokeDasharray="none"
                        className="hover:opacity-85 cursor-pointer transition-opacity"
                        style={{ transformOrigin: "center" }}
                      >
                        <title>{`${seg.model}: ${(seg.percentage * 100).toFixed(0)}%`}</title>
                      </path>
                    ))}
                    {/* Inner hollow maskcircle dynamically matches background theme variable */}
                    <circle cx="50" cy="50" r="33" fill="var(--card-bg)" className="transition-colors duration-150" />
                  </svg>
                  {/* Donut Center label */}
                  <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                    <p className="text-lg font-medium text-primary-text font-mono leading-none">{stats.total_messages}</p>
                    <p className="text-[7px] text-muted-text uppercase tracking-wider mt-0.5">Invocations</p>
                  </div>
                </div>

                <div className="flex flex-wrap gap-x-3 gap-y-1.5 justify-center pt-1">
                  {modelBreakdown.map((item, idx) => (
                    <div key={idx} className="flex items-center gap-1.5 text-[9px] font-mono">
                      <span
                        className="w-2 h-2 rounded-full shrink-0"
                        style={{ backgroundColor: getBadgeColors(item.model).color }}
                      />
                      <span className="text-secondary-text truncate max-w-[90px] font-medium">{formatModelName(item.model)}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Model Ledgers */}
              <div className="p-6 rounded-xl border border-card-border bg-card-bg md:col-span-7 space-y-4">
                <h3 className="text-[10px] font-bold text-secondary-text uppercase tracking-wider">Routing Breakdown</h3>
                <div className="space-y-4">
                  {modelBreakdown.map((item, idx) => {
                    const badge = getBadgeColors(item.model);
                    const pct = (item.count / totalModelCalls) * 100;
                    return (
                      <div key={idx} className="space-y-1.5">
                        <div className="flex justify-between items-center text-xs">
                          <span className={`px-2 py-0.5 rounded-full text-[8px] uppercase tracking-wider ${badge.className}`}>
                            {formatModelName(item.model)}
                          </span>
                          <span className="text-secondary-text text-[9px] font-mono font-semibold">
                            {item.count} Invocations ({pct.toFixed(0)}%)
                          </span>
                        </div>
                        <div className="w-full h-1.5 rounded-full bg-muted-surface overflow-hidden border border-card-border">
                          <div
                            className="h-full rounded-full transition-all duration-300"
                            style={{
                              width: `${pct}%`,
                              backgroundColor: badge.color,
                            }}
                          />
                        </div>
                        <div className="flex justify-between text-[9px] text-muted-text font-mono px-0.5">
                          <span>Tokens: {(item.input_tokens + item.output_tokens).toLocaleString()}</span>
                          <span>Cost: ${item.cost.toFixed(5)}</span>
                          <span className="text-success-val font-bold">Saved: ${item.savings.toFixed(5)}</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Savings Growth visual index */}
            <div className="p-6 rounded-xl border border-card-border bg-card-bg">
              <h3 className="text-[11px] font-medium text-zinc-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                <TrendingUp className="text-success-val w-3.5 h-3.5" />
                Comparative Savings Indicator (Savings vs Cost)
              </h3>
              <div className="w-full h-20 flex items-end gap-1.5 px-2 relative pt-6 border-b border-card-border">
                {/* Visual bars representing comparative metrics */}
                <div className="flex-1 flex flex-col justify-end items-center h-full">
                  <div
                    className="w-full bg-accent-violet/10 border border-accent-violet/30 rounded-t transition-all duration-300"
                    style={{ height: `${Math.min(100, (stats.total_cost / (stats.total_savings || 1)) * 100 + 10)}%` }}
                  />
                  <span className="text-[8px] text-secondary-text mt-1 font-mono uppercase tracking-wide">Total Cost</span>
                </div>
                
                <div className="flex-1 flex flex-col justify-end items-center h-full">
                  <div
                    className="w-full bg-success-val/10 border border-success-val/30 rounded-t transition-all duration-300"
                    style={{ height: "90%" }}
                  />
                  <span className="text-[8px] text-success-val mt-1 font-mono uppercase tracking-wide">Total Savings</span>
                </div>

                <div className="absolute top-2 left-4 text-[9px] text-muted-text font-mono">
                  ⚡ Operational efficiency factor:{" "}
                  <span className="text-success-val font-medium">
                    {(stats.total_savings / (stats.total_cost || 0.0001)).toFixed(1)}x
                  </span>{" "}
                  more cost effective than always premium routing.
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
